### PR TITLE
collaboration tagfilter <-> include plugins?

### LINKED ISSUE #25: collaboration tagfilter <-> include plugins?
I would be interested to combine features of the tagfilter and include plugins as follows:

* Embed the form of the tagfilter plugin
* Instead of listing the hyperlinks of the pages containing the tags, embed the pages themselves using the include plugin.

My plan would be,

1. Expose the include plugin's render function via a helper class,
2. Use it inside the tagfilter plugin. Refactoring is necessary.

Are you interested concerning your plugin? If so, I would elaborate deeper and make a pull request.

### PR DESCRIPTION
**Pull request by fjf2002**
Fixes #25.

~~Only works with include plugin PR https://github.com/dokufreaks/plugin-include/pull/296.~~
**EDIT:** Works without modification of the include plugin.

A new `include` tag is introduced with syntax
* `include`, or
* `include=semicolon;separated;include;plugin;options`

Request for comments.

### CODE REVIEW

**Comment by fjf2002** [comment]
OK it now works without modification of the include plugin.

In script.js I took the freedom to make some filtering code shorter and independent of jQuery.

Also fixes the problem that the `noneonclear` flag didn't work with pagelist `style=simplelist`.

**Comment by fjf2002** [comment]
**ping** any news here?

**Comment by fjf2002** [comment]
*ping* any news here? Any interest to include this feature?

**Comment by fjf2002** [comment]
*ping* any interest to merge this?

**Comment by Klap-in** [comment]
I have to test before I can say something about this PR.

I think we need @peterfromearth for merging. @peterfromearth do you have time to have a look?

**Comment by fjf2002** [comment]
@Klap-in: Any news here? Can I help somehow to bring forward this PR?

**Comment by peterfromearth** [comment]
@fjf2002 can you resolve the conflicts, will merge it then :)

**Comment by fjf2002** [comment]
@peterfromearth: Thanks for your response. I have resolved the conflicts.

**Pull request merged**
